-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;



CREATE TABLE IF NOT EXISTS public."waterLevel"
(
    id integer NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    value double precision NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."moistureLevel"
(
    id integer NOT NULL,
    sensor1 double precision NOT NULL,
    sensor2 double precision NOT NULL,
    sensor3 double precision NOT NULL,
    sensor4 double precision NOT NULL,
    sensor5 double precision NOT NULL,
    sensor6 double precision NOT NULL,
    sensor7 double precision NOT NULL,
    sensor8 double precision NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.temperature
(
    id integer NOT NULL,
    value double precision NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.photos
(
    id integer NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    filepath text NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.light
(
    id integer NOT NULL,
    value double precision NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);
END;